### ISSUE TITLE
Modding documentation

### ISSUE THREAD

**Issue by uku1928** [IonutParau/thepuzzlecell#32]
Is there any proper documentation for modding yet?
If not, it's just something to keep in mind before releasing the next big update.

**Comment by IonutParau** [comment]
The modding API is currently incomplete.
I plan on making the documentation after I add the terminal, macros and workspaces.

Until then, I'll keep this issue open

**Comment by uku1928** [comment]
so I guess I am not getting a documentation until 2.3.2

**Comment by IonutParau** [comment]
no, modding docs are going to be made soon

its just that stuff like Math interop, Mechanical interop and Master cell interop won'tbe a thing until 2.3.2

**Comment by IonutParau** [comment]
ok so I'll get to work on a simple Lua file for documentation inside of the IDE, then a markdown file to serve as a help page

**Comment by uku1928** [comment]
Since, as you said in #devlog, "modding API documentation is now basically complete".
Thus, this issue has been solved.
Now for me to close this issue and make a mod named "Lunar Suggestion Bag" as soon as I read the documentation.
